<?php

namespace BonoboBundle\Repository;

/**
 * BonoboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonoboRepository extends \Doctrine\ORM\EntityRepository
{
}
